name: DevSecOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    - name: Run tfsec (Terraform Security Scan)
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        directory: ./terraform

    - name: Build Docker image
      run: docker build -t myapp:latest .

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: myapp:latest
        format: 'table'

    - name: Install kubeseal
      run: |
        wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.25.0/kubeseal-0.25.0-linux-amd64.tar.gz
        tar -xvzf kubeseal-0.25.0-linux-amd64.tar.gz
        sudo install -m 755 kubeseal /usr/local/bin/kubeseal

    - name: Apply Sealed Secret
      run: |
        kubectl apply -f k8s/sealedsecret.yaml

    - name: Apply Kubernetes Deployment
      run: |
        kubectl apply -f k8s/deployment.yaml
