name: DevSecOps CI/CD

on:
  push:
    branches:
      - main

jobs:
  devsecops-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    - name: Run tfsec (Terraform Security Scan)
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
       working_directory: ./terraform

    - name: Build Docker image
      run: docker build -t myapp:latest .

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@0.11.2  # or latest stable version
      with:
        image-ref: myapp:latest
        format: 'table'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up kubeconfig for EKS
      run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}



    - name: Install kubeseal
      run: |
        wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.25.0/kubeseal-0.25.0-linux-amd64.tar.gz
        tar -xvzf kubeseal-0.25.0-linux-amd64.tar.gz
        sudo install -m 755 kubeseal /usr/local/bin/kubeseal

    - name: Apply Sealed Secret
      run: |
        kubectl apply -f k8s/sealedsecret.yaml

    - name: Apply Kubernetes Deployment
      run: |
        kubectl apply -f k8s/deployment.yaml
